[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=(A=1823396784,B=1298598689,C=1743498150,D=-2048051714)
ProjectName=Third Person Game Template

[/Script/EngineSettings.GeneralProjectSettings]
ProjectName=APBReloaded
Description=Private offline 1:1 APB Reloaded recreation
CompanyName=APBReloaded Offline
Homepage=https://apbdb.com/
bStartInVR=False

; APB multiplayer foundation

[APBServer]
WorldPort=17778
WorldPersistDir=
