#!/usr/bin/env python3
"""Parse ApbPrivateServer C# opcode enums + Character fields into project constants.

Pure regex against real Steam PrivateServer sources — unit-tested.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

TOOLS_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = TOOLS_ROOT / "source_registry.json"
REGISTRY = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
PROJECT = TOOLS_ROOT.parent
SCRATCH_DEFAULT = Path(r"C:\Users\Support\AppData\Local\Temp\grok-goal-e6df5b4a9676\implementer")


def resolve_source_root(alias: str) -> Path:
    resolver = TOOLS_ROOT / "scripts" / "resolve_source_root.ps1"
    completed = subprocess.run(
        [
            "pwsh",
            "-NoProfile",
            "-File",
            str(resolver),
            "-Alias",
            alias,
            "-Preflight",
            "-RegistryPath",
            str(REGISTRY_PATH),
        ],
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or completed.stdout.strip())
    return Path(completed.stdout.strip())


RETAIL_ROOT = resolve_source_root("retail_steam")
STEAM_PS = RETAIL_ROOT / REGISTRY["roots"]["retail_steam"]["apb_private_server_subpath"]

LOBBY_OPODES = STEAM_PS / "LobbyServer" / "TCP" / "Opodes.cs"
WORLD_OPCODES = STEAM_PS / "WorldServer" / "Tcp" / "Opcodes.cs"
DB_CHARACTER = STEAM_PS / "Common" / "DBCharacter.cs"


def parse_csharp_enum_opcodes(text: str) -> dict[str, int]:
    """Extract NAME = 0xHEX or NAME = decimal from C# enum body."""
    out: dict[str, int] = {}
    # skip comments
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("//") or line.startswith("/*") or line.startswith("*"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*,?", line)
        if m:
            name, val = m.group(1), m.group(2)
            out[name] = int(val, 0)
    return out


def parse_dbcharacter_fields(text: str) -> list[str]:
    """Public property names on DBCharacter (DataElement fields)."""
    fields: list[str] = []
    for m in re.finditer(
        r"public\s+(?:byte|int|string|byte\[\]|bool|UInt16|uint|long)\s+(\w+)\s*\{",
        text,
    ):
        fields.append(m.group(1))
    # also property style already covered
    return fields


def load_privateserver_map(
    lobby_path: Path = LOBBY_OPODES,
    world_path: Path = WORLD_OPCODES,
    char_path: Path = DB_CHARACTER,
) -> dict:
    lobby = parse_csharp_enum_opcodes(lobby_path.read_text(encoding="utf-8", errors="ignore"))
    world = parse_csharp_enum_opcodes(world_path.read_text(encoding="utf-8", errors="ignore"))
    fields = parse_dbcharacter_fields(char_path.read_text(encoding="utf-8", errors="ignore"))
    return {
        "source": {
            "lobby_opcodes": str(lobby_path),
            "world_opcodes": str(world_path),
            "db_character": str(char_path),
        },
        "lobby": lobby,
        "world": world,
        "character_fields": fields,
        "ue_domain_alignment": {
            "LoginAccount": "Lobby ASK_LOGIN / LOGIN_PROOF / ANS_LOGIN_SUCCESS",
            "CreateCharacter": "Lobby ASK_CHARACTER_CREATE / ANS_CHARACTER_CREATE",
            "EnterWorld": "Lobby ASK_WORLD_ENTER / World ASK_WORLD_ENTER",
            "JoinDistrict": "World ASK_DISTRICT_ENTER / ANS_DISTRICT_ENTER / DISTRICT_LIST",
            "SessionPhase::Boot": "pre-login",
            "SessionPhase::LoggedIn": "after ANS_LOGIN_SUCCESS",
            "SessionPhase::WorldLobby": "after WORLD_LIST / ANS_WORLD_ENTER",
            "SessionPhase::District": "after ANS_DISTRICT_ENTER",
            "CharacterProfile.name": "DBCharacter.Name",
            "CharacterProfile.faction": "DBCharacter.Faction (Enforcer/Criminal)",
            "cash": "DBCharacter.Money",
            "threat": "DBCharacter.Threat",
        },
        "reuse_notes": [
            "ApbPrivateServer is a partial 2011-era C# lobby/world emu — not a drop-in UE runtime.",
            "Opcodes and character fields are reusable as protocol knowledge for Domain offline parity.",
            "Do not claim full modern live-client fidelity; many world opcodes are stubs in the emu.",
            "UE offline Domain already implements login/character/district without TCP; opcodes document mapping.",
        ],
    }


def emit_cpp_header(data: dict, out: Path) -> None:
    lines = [
        "// Auto-generated by tools/convert/parse_privateserver.py — DO NOT hand-edit values.",
        "// Source: ApbPrivateServer Lobby Opodes.cs + World Opcodes.cs",
        "#pragma once",
        "#include <cstdint>",
        "namespace apb { namespace privateserver {",
        "namespace lobby {",
        "enum class Opcode : uint32_t {",
    ]
    for name, val in sorted(data["lobby"].items(), key=lambda x: x[1]):
        lines.append(f"\t{name} = {val}u, // 0x{val:X}")
    lines += [
        "};",
        "} // namespace lobby",
        "namespace world {",
        "enum class Opcode : uint32_t {",
    ]
    for name, val in sorted(data["world"].items(), key=lambda x: x[1]):
        lines.append(f"\t{name} = {val}u, // 0x{val:X}")
    lines += [
        "};",
        "} // namespace world",
        "",
        "/** Map Domain session phase to private-server conceptual stage (documentation + tools). */",
        "inline const char* DomainPhaseToPrivateServerStage(const char* phase) {",
        '\tif (!phase) return "unknown";',
        '\tif (phase[0]==\'B\') return "pre_login"; // Boot',
        '\tif (phase[0]==\'L\') return "post_ANS_LOGIN_SUCCESS"; // LoggedIn',
        '\tif (phase[0]==\'W\') return "world_lobby"; // WorldLobby',
        '\tif (phase[0]==\'D\') return "in_district"; // District',
        '\treturn "unknown";',
        "}",
        "",
        "inline uint32_t LobbyAskLogin() { return static_cast<uint32_t>(lobby::Opcode::ASK_LOGIN); }",
        "inline uint32_t LobbyAskCharacterCreate() { return static_cast<uint32_t>(lobby::Opcode::ASK_CHARACTER_CREATE); }",
        "inline uint32_t WorldAskDistrictEnter() { return static_cast<uint32_t>(world::Opcode::ASK_DISTRICT_ENTER); }",
        "}} // namespace apb::privateserver",
        "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")


def emit_report(data: dict, path: Path) -> None:
    lines = [
        "# ApbPrivateServer reuse report",
        "",
        "## What it is",
        "C# multi-process emu (Lobby / Character / World / File) under Steam `ApbPrivateServer`.",
        "Partial protocol surface (~2011 APS). **Not** a UE5 game runtime.",
        "",
        "## Reusable",
        "- Lobby + World **opcode numbers** (wired into `APBPrivateServerOpcodes.h`)",
        "- `DBCharacter` fields: Name, Faction, Gender, Money, Rank, Threat, Custom → Domain CharacterProfile alignment",
        "- Flow: login → character create/list → world list → world enter → district enter",
        "",
        "## Not reusable as-is",
        "- C# TCP servers replacing UE Domain",
        "- Incomplete world handlers / modern client features",
        "- DB stack (FrameWork) for UE shipping",
        "",
        "## Concrete reuse in this project",
        "- Generated `Source/APBReloaded/Domain/APBPrivateServerOpcodes.h`",
        "- JSON map `Content/Extracted/Convert/privateserver_opcodes.json`",
        "- Domain phase ↔ private-server stage helper",
        "- Unit test reads **real** Opodes.cs / Opcodes.cs / DBCharacter.cs",
        "",
        f"## Lobby opcodes ({len(data['lobby'])})",
    ]
    for n, v in sorted(data["lobby"].items(), key=lambda x: x[1])[:20]:
        lines.append(f"- `{n}` = 0x{v:X} ({v})")
    lines.append(f"\n## World opcodes ({len(data['world'])}) — sample")
    for n, v in sorted(data["world"].items(), key=lambda x: x[1])[:15]:
        lines.append(f"- `{n}` = 0x{v:X}")
    lines.append("\n## Character fields")
    for f in data["character_fields"]:
        lines.append(f"- {f}")
    lines.append("\n## UE Domain alignment")
    for k, v in data["ue_domain_alignment"].items():
        lines.append(f"- **{k}**: {v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scratch", type=Path, default=SCRATCH_DEFAULT)
    ap.add_argument("--steam-root", type=Path)
    ap.add_argument("--project-root", type=Path, default=PROJECT)
    ap.add_argument("--out", type=Path)
    args = ap.parse_args()
    if args.steam_root is not None and args.steam_root.resolve() != RETAIL_ROOT.resolve():
        raise RuntimeError("--steam-root must equal the canonical retail_steam resolver result")
    private_server_root = STEAM_PS
    lobby_path = private_server_root / "LobbyServer" / "TCP" / "Opodes.cs"
    world_path = private_server_root / "WorldServer" / "Tcp" / "Opcodes.cs"
    char_path = private_server_root / "Common" / "DBCharacter.cs"
    data = load_privateserver_map(lobby_path, world_path, char_path)
    out_json = args.project_root / "Content" / "Extracted" / "Convert" / "privateserver_opcodes.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(data, indent=2), encoding="utf-8")
    args.scratch.mkdir(parents=True, exist_ok=True)
    (args.scratch / "privateserver_opcodes.json").write_text(json.dumps(data, indent=2), encoding="utf-8")
    header_out = args.out or args.project_root / "Source" / "APBReloaded" / "Domain" / "APBPrivateServerOpcodes.h"
    emit_cpp_header(data, header_out)
    emit_report(data, args.project_root / "tools" / "convert" / "PRIVATESERVER_REUSE.md")
    emit_report(data, args.scratch / "privateserver_reuse.md")
    print(f"resolved_steam_root={RETAIL_ROOT}")
    print(f"resolved_project_root={args.project_root}")
    print(f"header_out={header_out}")
    print(
        f"lobby={len(data['lobby'])} world={len(data['world'])} "
        f"ASK_LOGIN=0x{data['lobby'].get('ASK_LOGIN',0):X} "
        f"ASK_DISTRICT_ENTER=0x{data['world'].get('ASK_DISTRICT_ENTER',0):X}"
    )
    return 0 if data["lobby"].get("ASK_LOGIN") == 0x3E8 else 2


if __name__ == "__main__":
    raise SystemExit(main())
